























#MEAN - 
# MongoDB
# Express
# Angular
# NodeJs

# docker container run --rm --name db01 -d -p 2701:2701 db

# docker container run --rm --name app01 -d -p 3000:3000 app

# docker container run --rm --name web01 -d -p 8080:80 web
